### ISSUE TITLE
issue in the common lisp configuration

### ISSUE THREAD

**Issue by gbataille** [OmerShapira/Syntactic#12]
in the clisp config file, a comma is missing line 19 in the makeprg definition

then it does not seem to work still. putting the comma removes the error but the plugin does not seem to intercept the output of the clisp properly. not gotten there yet

**Comment by berak** [comment]
hmm, just out of curiosity, something broken on github ? 

why would i recieve a notification email of this issue closed ? i'm not at all involved here ..
nvm, go on with your good work, just wondering ..

**Comment by yuvadm** [comment]
you've never seen this repo before? weird. maybe teh githubz are b0rked.
